# InfraWatch — Urban Infrastructure Risk Intelligence Engine
# Config: Road Segment Definitions

SEGMENTS = {
    # --- NORTH ZONE ---
    "SEG-N01": {
        "name": "NH-48 Gurugram Flyover",
        "zone": "North",
        "road_type": "Highway",
        "base_condition": 45,
        "drainage_quality": "Poor",
        "maintenance_history_score": 30,
        "length_km": 4.2,
    },
    "SEG-N02": {
        "name": "GT Karnal Road",
        "zone": "North",
        "road_type": "Arterial",
        "base_condition": 60,
        "drainage_quality": "Fair",
        "maintenance_history_score": 55,
        "length_km": 3.8,
    },
    "SEG-N03": {
        "name": "Rohini Sector-7 Internal",
        "zone": "North",
        "road_type": "Residential",
        "base_condition": 35,
        "drainage_quality": "Poor",
        "maintenance_history_score": 20,
        "length_km": 1.2,
    },
    "SEG-N04": {
        "name": "Pitampura Main Road",
        "zone": "North",
        "road_type": "Arterial",
        "base_condition": 70,
        "drainage_quality": "Good",
        "maintenance_history_score": 75,
        "length_km": 2.5,
    },
    "SEG-N05": {
        "name": "Wazirabad Bridge Approach",
        "zone": "North",
        "road_type": "Highway",
        "base_condition": 40,
        "drainage_quality": "Poor",
        "maintenance_history_score": 25,
        "length_km": 1.8,
    },
    # --- SOUTH ZONE ---
    "SEG-S01": {
        "name": "Mehrauli-Badarpur Road",
        "zone": "South",
        "road_type": "Arterial",
        "base_condition": 55,
        "drainage_quality": "Fair",
        "maintenance_history_score": 45,
        "length_km": 5.1,
    },
    "SEG-S02": {
        "name": "Saket District Centre",
        "zone": "South",
        "road_type": "Residential",
        "base_condition": 80,
        "drainage_quality": "Good",
        "maintenance_history_score": 85,
        "length_km": 1.5,
    },
    "SEG-S03": {
        "name": "Chattarpur Enclave Road",
        "zone": "South",
        "road_type": "Residential",
        "base_condition": 30,
        "drainage_quality": "Poor",
        "maintenance_history_score": 15,
        "length_km": 2.0,
    },
    "SEG-S04": {
        "name": "Faridabad Highway Stretch",
        "zone": "South",
        "road_type": "Highway",
        "base_condition": 65,
        "drainage_quality": "Fair",
        "maintenance_history_score": 60,
        "length_km": 6.3,
    },
    "SEG-S05": {
        "name": "Tughlaqabad Flyover",
        "zone": "South",
        "road_type": "Highway",
        "base_condition": 50,
        "drainage_quality": "Fair",
        "maintenance_history_score": 40,
        "length_km": 2.2,
    },
    # --- EAST ZONE ---
    "SEG-E01": {
        "name": "Vikas Marg",
        "zone": "East",
        "road_type": "Arterial",
        "base_condition": 55,
        "drainage_quality": "Fair",
        "maintenance_history_score": 50,
        "length_km": 4.0,
    },
    "SEG-E02": {
        "name": "Anand Vihar Flyover",
        "zone": "East",
        "road_type": "Highway",
        "base_condition": 70,
        "drainage_quality": "Good",
        "maintenance_history_score": 70,
        "length_km": 1.8,
    },
    "SEG-E03": {
        "name": "Trilokpuri Internal",
        "zone": "East",
        "road_type": "Residential",
        "base_condition": 25,
        "drainage_quality": "Poor",
        "maintenance_history_score": 10,
        "length_km": 0.9,
    },
    "SEG-E04": {
        "name": "NH-24 Bypass",
        "zone": "East",
        "road_type": "Highway",
        "base_condition": 60,
        "drainage_quality": "Fair",
        "maintenance_history_score": 55,
        "length_km": 7.5,
    },
    "SEG-E05": {
        "name": "Patparganj Industrial Road",
        "zone": "East",
        "road_type": "Arterial",
        "base_condition": 45,
        "drainage_quality": "Poor",
        "maintenance_history_score": 35,
        "length_km": 2.8,
    },
    # --- WEST ZONE ---
    "SEG-W01": {
        "name": "Najafgarh Road",
        "zone": "West",
        "road_type": "Arterial",
        "base_condition": 40,
        "drainage_quality": "Poor",
        "maintenance_history_score": 30,
        "length_km": 5.5,
    },
    "SEG-W02": {
        "name": "Janakpuri District Centre",
        "zone": "West",
        "road_type": "Residential",
        "base_condition": 75,
        "drainage_quality": "Good",
        "maintenance_history_score": 80,
        "length_km": 1.3,
    },
    "SEG-W03": {
        "name": "Dwarka Expressway Link",
        "zone": "West",
        "road_type": "Highway",
        "base_condition": 85,
        "drainage_quality": "Good",
        "maintenance_history_score": 90,
        "length_km": 4.0,
    },
    "SEG-W04": {
        "name": "Palam Colony Internal",
        "zone": "West",
        "road_type": "Residential",
        "base_condition": 28,
        "drainage_quality": "Poor",
        "maintenance_history_score": 12,
        "length_km": 1.1,
    },
    "SEG-W05": {
        "name": "Tikri Border Road",
        "zone": "West",
        "road_type": "Arterial",
        "base_condition": 50,
        "drainage_quality": "Fair",
        "maintenance_history_score": 40,
        "length_km": 3.2,
    },
}

# Drainage multiplier (used in risk & prediction)
DRAINAGE_MULTIPLIER = {
    "Good": 0.3,
    "Fair": 0.6,
    "Poor": 1.0,
}

# Road type traffic multiplier
ROAD_TYPE_TRAFFIC = {
    "Highway": 1.0,
    "Arterial": 0.7,
    "Residential": 0.3,
}
